DIRETORIO_IOACAS = "datasets/IOACAS_QBH/"
DIRETORIO_MIR = "datasets/MIR-QBSH-corpus/"


ARQUIVO_MIDI = "midi.list"
ARQUIVO_QUERY = "query.list"

DATASET_MIR = DIRETORIO_MIR + ARQUIVO_MIDI
DATASET_IOACAS = DIRETORIO_IOACAS + ARQUIVO_MIDI
