DIRETORIO_IOACAS = "datasets/IOACAS_QBH/"
DIRETORIO_MIR = "datasets/MIR-QBSH-corpus/"


PASTA_DATASET = "midiFile/"
#PASTA_QUERIES = "waveFile/"



ARQUIVO_LISTA_MIDI = "midi.list"

ARQUIVO_LISTA_QUERY_IOACAS = "query.list"
ARQUIVO_LISTA_QUERY_MIR = "query-wav.list"
#ARQUIVO_LISTA_QUERY_MIR = "query-pv.list"  #caso se deseje fazer query em pv, descomentar essa linha e comentar a de cima




DATASET_IOACAS = DIRETORIO_IOACAS + ARQUIVO_LISTA_MIDI
DATASET_MIR = DIRETORIO_MIR + ARQUIVO_LISTA_MIDI

QUERIES_IOACAS = DIRETORIO_IOACAS + ARQUIVO_LISTA_QUERY_IOACAS
QUERIES_MIR = DIRETORIO_MIR + ARQUIVO_LISTA_QUERY_MIR
